import type { NextPage } from "next";
import { useGoogleLogin } from "react-google-login";
import Head from "next/head";

const Login: NextPage = () => {
  const { signIn } = useGoogleLogin({
    clientId: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? "",
  });
  signIn();
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-10 flex flex-col items-center w-full h-full justify-between"></main>
    </>
  );
};

export default Login;
