import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Avatar from "../components/atom/Avatar";
import Box from "../components/atom/Box";
import Button from "../components/atom/Button";
import Chips from "../components/atom/Chips";
import Modal from "../components/atom/Modal";
import Text from "../components/atom/Text";
import TextField from "../components/atom/TextField";
import { AddImageIcon, PlusIcon, SearchIcon } from "../components/icons";
import Heeader from "../components/organisms/Header";

const NewPoll: NextPage = () => {
  const [tagsModal, setTagsModal] = useState(false);
  return (
    <div className="container mx-auto p-8 flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heeader />
      <main className="pt-5 flex-1 flex flex-col justify-between">
        <Box className="space-y-5">
          <Box className="w-full h-32 flex flex-col space-y-2 justify-center items-center border border-dashed border-[#D5D7DA] rounded-md">
            <AddImageIcon color="#000" />
            <Text fontSize="sm" fontWeight="medium">
              Add Cover
            </Text>
          </Box>
          <TextField placeholder="Type ask a question" />
          <TextField placeholder="Option 1" />
          <TextField placeholder="Option 2" />
          <Button variant="outlined" className="flex justify-center items-center">
            <PlusIcon color="#000" />
          </Button>
          <Box className="flex items-center space-x-3">
            <Avatar src="/jojo.jpg" />
            <Text fontWeight="medium">Mohammad</Text>
          </Box>
          <Button
            variant="text"
            className="flex justify-start items-center space-x-2"
            onClick={() => setTagsModal(true)}
          >
            <PlusIcon color="#000" />
            <Text fontWeight="medium">Add Tags</Text>
          </Button>
        </Box>
        <Button>Publish</Button>
      </main>

      <Modal isOpen={tagsModal} onClose={() => setTagsModal(false)}>
        <TextField placeholder="Search tags ..." beforElement={<SearchIcon color="#283138" />} />
        <div className="max-h-[16rem] py-5 flex flex-wrap gap-3 overflow-auto">
          <Chips>FOOD</Chips>
          <Chips>FOOD</Chips>
          <Chips>FOOD</Chips>
          <Chips>FOOD</Chips>
          <Chips>FOOD</Chips>
        </div>
      </Modal>
    </div>
  );
};

export default NewPoll;
