import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Box from "../components/atom/Box";
import Button from "../components/atom/Button";
import Text from "../components/atom/Text";
import TextField from "../components/atom/TextField";
import { CloseEyeIcon, GoogleIcon, OpenEyeIcon } from "../components/icons";
import { Handshake } from "../components/illustrations";
import Heeader from "../components/organisms/Header";

const Login: NextPage = () => {
  const router = useRouter();
  const [shouldShowPassword, setShouldShowPassword] = useState(false);

  const handleShowPassword = () => {
    setShouldShowPassword(!shouldShowPassword);
  };

  return (
    <div className="container mx-auto p-8 flex flex-col h-screen">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heeader />
      <main className="pt-10 flex flex-col items-center w-full justify-between flex-1">
        <Box className="w-full flex flex-col items-center">
          <Box className="w-full flex justify-center items-center h-40">
            <Handshake color="#000" />
          </Box>
          <Box className="flex flex-col w-full space-y-4 mt-10">
            <Box className="w-full space-y-2">
              <Text fontWeight="medium" fontSize="sm">
                Email
              </Text>
              <TextField />
            </Box>
            <Box className="w-full space-y-2">
              <Text fontWeight="medium" fontSize="sm">
                Password
              </Text>
              <TextField
                type={shouldShowPassword ? "text" : "password"}
                afterElement={
                  shouldShowPassword ? (
                    <CloseEyeIcon color="#000" onClick={handleShowPassword} />
                  ) : (
                    <OpenEyeIcon color="#000" onClick={handleShowPassword} />
                  )
                }
              />
            </Box>
            <Box className="w-full space-y-2">
              <Text fontWeight="medium" fontSize="sm">
                Password
              </Text>
              <TextField
                type={shouldShowPassword ? "text" : "password"}
                afterElement={
                  shouldShowPassword ? (
                    <CloseEyeIcon color="#000" onClick={handleShowPassword} />
                  ) : (
                    <OpenEyeIcon color="#000" onClick={handleShowPassword} />
                  )
                }
              />
            </Box>
            <Button>Register</Button>
          </Box>
        </Box>
        <Box className="flex flex-col space-y-3 w-full">
          <Button variant="text" onClick={() => router.push("/login")}>
            I'm have account. <strong className="underline">login</strong>
          </Button>
          <Button variant="outlined">
            <Box className="flex justify-center space-x-2">
              <GoogleIcon color="#000" />
              <Text fontWeight="medium">SignUp with Google</Text>
            </Box>
          </Button>
        </Box>
      </main>
    </div>
  );
};

export default Login;
