import type { GetServerSideProps, NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Avatar from "../../components/atom/Avatar";
import Box from "../../components/atom/Box";
import Chips from "../../components/atom/Chips";
import Text from "../../components/atom/Text";
import Option from "../../components/molecules/Option";
import { getVote } from "../../apis/votes/getOne/api";
import { useMe } from "../../apis/auth/me/hook";
import Layout from "../../components/Layout";
import { useVote } from "../../apis/votes/vote/hook";
import Image from "next/image";
import Link from "next/link";

interface Props {
  poll: [];
}

const NewPoll: NextPage<Props> = ({ poll }) => {
  const vote = useVote();

  const submitVote = (optionId: string) => {
    vote.mutate({
      id: poll.id,
      option_id: optionId,
    });
  };

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col space-y-5">
        {poll.cover && (
          <Image
            src={`${process.env.NEXT_PUBLIC_API_BASE_URL}/covers/${poll.cover}`}
            width="100"
            height="100"
            alt={poll.title}
            className="rounded-lg"
          />
        )}
        <Text dir="auto" fontWeight="bold" fontSize="lg">
          {poll.title}
        </Text>
        <Box className="flex flex-col space-y-3">
          {poll.options.map((option) => (
            <Option
              key={option.id}
              title={option.title}
              percentage={option.percentage}
              checked={option.is_user_voted}
              submit={() => submitVote(option.id.toString())}
            />
          ))}
        </Box>
        <Box className="flex items-center space-x-3">
          <Avatar src="/jojo.jpg" />
          <Text fontWeight="medium">{poll.owner.username}</Text>
        </Box>
        <Box className="flex max-h-[7rem] flex-wrap gap-2 overflow-auto">
          {poll.tags.map((tag) => (
            <Link key={tag.id} href={`/tags/${tag.id}`}>
              <a>
                <Chips>{tag.title}</Chips>
              </a>
            </Link>
          ))}
        </Box>
        <Box className="border border-solid border-black rounded-lg p-4 flex items-center justify-between">
          <Text fontWeight="medium">https://votely.app/{poll.short_identifier}</Text>
          <Box className="flex items-center space-x-2">
            <Text fontWeight="medium">Copy</Text>
            <svg
              width="21"
              height="21"
              viewBox="0 0 21 21"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M2.58321 3.07089C1.79504 3.93102 1.79504 5.26434 1.79504 7.93099C1.79504 10.5976 1.79504 11.931 2.58321 12.7911C2.64218 12.8554 2.70392 12.9172 2.76827 12.9762C3.62841 13.7643 4.96173 13.7643 7.62838 13.7643C10.295 13.7643 11.6283 13.7643 12.4885 12.9762C12.5528 12.9172 12.6146 12.8554 12.6735 12.7911C13.4617 11.931 13.4617 10.5976 13.4617 7.93099C13.4617 5.26434 13.4617 3.93102 12.6735 3.07089C12.6146 3.00654 12.5528 2.94479 12.4885 2.88582C11.6283 2.09766 10.295 2.09766 7.62838 2.09766C4.96173 2.09766 3.62841 2.09766 2.76827 2.88582C2.70392 2.94479 2.64218 3.00654 2.58321 3.07089ZM13.6006 7.84766C14.4823 7.84766 15.097 7.84828 15.5749 7.88864C16.0437 7.92822 16.3122 8.00195 16.5151 8.10949C16.9133 8.32045 17.2389 8.64609 17.4499 9.04424C17.5574 9.24721 17.6312 9.51569 17.6707 9.98443C17.7111 10.4624 17.7117 11.077 17.7117 11.9588V12.931C17.7117 14.2842 17.7103 15.228 17.6192 15.9438C17.5305 16.6404 17.3678 17.0146 17.1206 17.2844C17.0764 17.3327 17.0301 17.379 16.9818 17.4232C16.7119 17.6705 16.3378 17.8331 15.6412 17.9218C14.9254 18.0129 13.9816 18.0143 12.6284 18.0143H11.6562C10.7744 18.0143 10.1598 18.0137 9.68181 17.9733C9.21308 17.9338 8.9446 17.86 8.74162 17.7525C8.34347 17.5415 8.01783 17.2159 7.80688 16.8177C7.69933 16.6148 7.6256 16.3463 7.58602 15.8776C7.54567 15.3996 7.54504 14.7849 7.54504 13.9032H6.04504V13.9364V13.9364C6.04504 14.7772 6.04503 15.4553 6.09134 16.0038C6.13904 16.5687 6.23987 17.0641 6.48143 17.52C6.83303 18.1836 7.37576 18.7263 8.03934 19.0779C8.49526 19.3195 8.9907 19.4203 9.55561 19.468C10.1041 19.5143 10.7821 19.5143 11.6228 19.5143H11.6229H11.6562H12.6284H12.68C13.9695 19.5143 15.009 19.5144 15.8306 19.4098C16.6823 19.3014 17.4049 19.07 17.9952 18.5291C18.0756 18.4554 18.1528 18.3782 18.2265 18.2978C18.7674 17.7075 18.9988 16.9849 19.1072 16.1332C19.2117 15.3116 19.2117 14.2721 19.2117 12.9826V12.931V11.9588V11.9256C19.2117 11.0848 19.2117 10.4067 19.1654 9.85822C19.1177 9.29331 19.0169 8.79787 18.7753 8.34195C18.4237 7.67837 17.881 7.13564 17.2174 6.78405C16.7615 6.54248 16.2661 6.44165 15.7011 6.39396C15.1527 6.34764 14.4746 6.34765 13.6339 6.34766H13.6338L13.6006 6.34766V7.84766Z"
                fill="black"
              />
            </svg>
          </Box>
        </Box>
      </main>
    </Layout>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const identifier = context.params?.identifier as string;
  // console.log(context.req.cookies);
  try {
    const { data: poll } = await getVote(identifier, context.req.cookies["votely.token"]);
    return {
      props: {
        poll,
      },
    };
  } catch (e) {
    console.log(e);
  }
  return {
    props: {
      poll: null,
    },
  };
};
export default NewPoll;
