import type { NextPage } from "next";
import Head from "next/head";
import TextField from "../../components/atom/TextField";
import { SearchIcon } from "../../components/icons";
import ActiveVoteBanner from "../../components/organisms/ActiveVoteBanner";
import Section from "../../components/molecules/Section";
import Box from "../../components/atom/Box";
import { useRouter } from "next/router";
import Layout from "../../components/Layout";

const Tags: NextPage = () => {
  const router = useRouter();
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="space-y-5 pb-32">
        <TextField placeholder="Search Tags ..." beforElement={<SearchIcon color="#283138" />} />
        <Section title="Top Categories">
          <Box className="flex items-center space-x-5">
            <Box className="w-20 h-20 bg-gray-100 rounded-lg" />
            <Box className="w-20 h-20 bg-gray-100 rounded-lg" />
            <Box className="w-20 h-20 bg-gray-100 rounded-lg" />
          </Box>
        </Section>
      </main>
    </Layout>
  );
};

export default Tags;
